framework:
    cache:
        # Configure cache pools
        app: cache.adapter.filesystem

        pools:
            # Statistics cache pool
            cache.fizzbuzz_statistics:
                adapter: cache.adapter.filesystem
                default_lifetime: 3600
