when@dev:
    _errors:
        resource: "@FrameworkBundle/Resources/config/routing/errors.php"
        prefix: /_error

# Enable attribute routing for controllers
custom_controllers_path:
    resource:
        path: ../../src/Presentation/Controller/
        namespace: App\Presentation\Controller
    type: attribute
